[package]
name = "random-candle-generator"
version = "0.1.0"
edition = "2021"
description = "Utilities for ohlc candle generation."
license = "MIT"
exclude = [
    "tmp/*",
]

[dependencies]
serde = "1.0.163"
rmp-serde = "1.1.1"
serde_derive = "1.0.163"

[dev-dependencies]
rand = "0.8.5"
